# == README ===
#   PROBLEM: 
#     when using gitpod with web IDE like vscode or browser-terminal, then if use remote port prepended urls (`gp ports list`), you will see
#     "Unable to find a matching sales channel for the request: "...". Please make sure the domain mapping is correct"
#   SOLUTION: 
#     MUST use gitpod local companion, then use http://localhost:8000/admin (must go admin!)
#       then add "sales channel" (default admin user/password: admin/shopware)
#       then http://localhost:8000 will work
#   Reference 
#     https://docs.dockware.io/use-dockware/default-credentials 
#     https://beamtic.com/unable-to-find-a-matching-sales-channel-shopware
#     https://www.gitpod.io/docs/references/ides-and-editors/browser-terminal
#     https://www.gitpod.io/docs/references/ides-and-editors/local-companion#gitpod-local-companion

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Shopware
    before: |
      echo 'alias admin-watch="APP_URL=http://localhost:8000 composer run watch:admin"' >> ~/.bashrc
    init: |
      docker pull mysql:8
      docker pull ghcr.io/shyim/shopware-docker/adminer
      composer config --global github-oauth.github.com $(printf '%s\n' host=github.com | gp credential-helper get | sort | head -2 | tail -1 | sed 's;password=;;')
      composer install
      docker run --restart always -d --name=mysql -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql:8
      docker run --restart always -d --name=adminer --link mysql:mysql -p 5000:8080 -e ADMINER_DESIGN=pepa-linha -e ADMINER_DEFAULT_SERVER=mysql -e ADMINER_PLUGINS="tables-filter table-structure json-column version-noverify" ghcr.io/shyim/shopware-docker/adminer
      ./bin/console system:setup -n --database-url "mysql://root:root@127.0.0.1:3306/shopware" --app-url "$(gp url 8000)" --app-env dev
      # Setup Trusted Proxies
      echo "TRUSTED_PROXIES=192.168.0.0/16" >> .env
      composer run setup
      
      ./bin/console framework:demodata --products 300 -e prod
      ./bin/console dal:refresh:index -e prod
    command: | 
      # prebuild docker containers persist to command phase, hence just simply docker start, no need to docker run
      #   also all db seeding work persist to this phase, nice! 
      docker start mysql
      docker start adminer
      ./bin/console system:setup -n --database-url "mysql://root:root@127.0.0.1:3306/shopware" --app-url "$(gp url 8000)" --app-env dev
      # Setup Trusted Proxies
      echo "TRUSTED_PROXIES=192.168.0.0/16" >> .env
      composer run setup
      
      ./bin/console framework:demodata --products 300 -e prod
      ./bin/console dal:refresh:index -e prod
      # Gitpod registers the ports on first docker command
      docker ps
      
      # Wait for port open
      gp ports await 3306
      
      # Wait until MySQL is reachable
      until mysqladmin ping; do
          sleep 1
      done
      
      # Update domain url
      ./bin/console sales-channel:update:domain $(gp url 8000 | awk -F[/:] '{print $4}')
      
      # Start Webserver
      symfony server:start --port 8000
  - name: Getting Started
    command: |
      echo 'Hey. Your environment is starting soon. You can see the progress in the Shopware Terminal'
      echo 'If you want to run the Admin Watch, just use the Terminal alias: admin-watch'
      echo 'Happy Coding!'
      echo "Shop URL: $(gp url 8000)"
      echo "Admin-Watcher URL: $(gp url 8080)"
      echo "Adminer URL: $(gp url 5000)"
ports:
  - name: Shopware
    port: 8000
    onOpen: open-browser
    description: Symfony Server
  - name: Admin-Watcher
    port: 8080
    onOpen: open-browser
    description: "Use Forward Proxy to localhost to access this service"
  - name: MySQL
    onOpen: ignore
    port: 3306
  - name: Adminer
    onOpen: ignore
    port: 5000

jetbrains:
  plugins:
    # tmy plugins
    - com.intellij.lang.jsgraphql
    - org.sonarlint.idea
    - com.intellij.ml.llm
    - com.sourcegraph.jetbrains
    - com.github.lppedd.idea-conventional-commit
    # from shopware repo 
    - com.jetbrains.php
    - com.intellij.php.tools.quality.phpstan
    - com.intellij.php.psalm
    - org.jetbrains.plugins.yaml
    - com.jetbrains.twig
    - fr.adrienbrault.idea.symfony2plugin
    - de.shyim.shopware6
    - de.shyim.ideaphpstantoolbox
    - de.espend.idea.php.annotation
  phpstorm:
    vmoptions: "-Xmx4g"

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - redhat.vscode-yaml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
